# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

ZSH_THEME="agnoster_colour"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.git clone https://github.com/reknitse/dotfiles.git
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$HOME/.zsh/custom

# Which plugins would you like to load?
plugins=(git zsh-syntax-highlighting perl history history-substring-search-min zsh-completions)
source $ZSH/oh-my-zsh.sh

# stderr in red
exec 2>>( while read X; do print "\e[91m${X}\e[0m" > /dev/tty; done & )

#########################################################
#########################################################

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/gregor/.local/bin"
export EDITOR=/usr/bin/vim
export SSH_COLOR=yellow

export DEFAULT_USER="gregor"

# in line search highlight
export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND="fg=green,bold"
export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND="fg=red,bold"

# probably for vim ???
[[ "$TERM" == "xterm" ]] && export TERM=xterm-256color

hash direnv 2>/dev/null && eval "$(direnv hook zsh)"
#########################################################

source ~/.aliasrc
source ~/.inputrc

#########################################################
#########################################################

# local settings:
if [[ -f ~/.zshrc_local ]]; then
    source ~/.zshrc_local
else
    touch ~/.zshrc_local
    source ~/.zshrc_local
fi

autoload -U compinit && compinit

source ~/.oh-my-zsh/plugins/per-directory-history/per-directory-history.zsh

# remove duplicates from history
setopt HIST_IGNORE_ALL_DUPS

